version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - ENV=production
    restart: unless-stopped

volumes:
  data:
  uploads: