version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db-init

  frontend:
    build: ./frontend  
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  db-init:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: python init_db.py
    restart: "no"

volumes:
  data: